defmodule DashboardSSD.Notifications.Alert do
  @moduledoc """
  Alerts generated by rules or system events for a project.

    - Persists alert messages and statuses tied to projects.
  - Validates required fields via its changeset.
  - Serializes minimal fields for API/LiveView usage.
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Ecto.Changeset

  @typedoc "Alert record"
  @type t :: %__MODULE__{
          id: integer() | nil,
          project_id: integer() | nil,
          message: String.t() | nil,
          status: String.t() | nil
        }

  @derive {Jason.Encoder, only: [:id, :project_id, :message, :status]}
  schema "alerts" do
    belongs_to :project, DashboardSSD.Projects.Project, type: :id
    field :message, :string
    field :status, :string
    timestamps(type: :utc_datetime)
  end

  @doc false
  @spec changeset(t() | Changeset.t(), map()) :: Changeset.t()
  def changeset(alert, attrs) do
    alert
    |> cast(attrs, [:project_id, :message, :status])
    |> validate_required([:project_id, :message, :status])
    |> foreign_key_constraint(:project_id)
  end
end
