import Config

# Configure your database
config :dashboard_ssd, DashboardSSD.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "dashboard_ssd_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
dev_secret_key_base =
  System.get_env("DEV_SECRET_KEY_BASE", String.duplicate("a", 64))

config :dashboard_ssd, DashboardSSDWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: dev_secret_key_base,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:dashboard_ssd, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:dashboard_ssd, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :dashboard_ssd, DashboardSSDWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/dashboard_ssd_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :dashboard_ssd, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

drive_service_account_path =
  System.get_env("DRIVE_SERVICE_ACCOUNT_JSON") ||
    System.get_env("GOOGLE_APPLICATION_CREDENTIALS") ||
    Path.expand("../priv/service_accounts/dev-drive-service-account.json", __DIR__)

drive_root_id = System.get_env("DRIVE_ROOT_FOLDER_ID")

config :dashboard_ssd, :shared_documents_integrations,
  drive: [
    service_account_json_path: drive_service_account_path,
    root_folder_id: drive_root_id
  ],
  notion: [
    token: System.get_env("NOTION_TOKEN") || "notion-dev-token",
    contracts_database_id:
      System.get_env("NOTION_CONTRACTS_DATABASE_ID") || "notion-contracts-db-dev",
    contracts_page_parent_id:
      System.get_env("NOTION_CONTRACTS_PAGE_PARENT_ID") || "notion-contracts-page-dev"
  ]
